### PR TITLE
FIT-416 - Investigate RSPEC Test Intake Pipeline Failures

### PR DESCRIPTION
**Pull request by SergiiRedchuk**
temporary remove the editing_participant_spec.rb to estimate test coverage difference

### Jira Story

- [Investigate RSPEC Test Intake Pipeline Failures FIT-416](https://osi-cwds.atlassian.net/browse/FIT-416)

### CODE REVIEW

**Comment by SergiiRedchuk** [comment]
retest this please

**Comment by SergiiRedchuk** [comment]
retest this please

**Comment by SergiiRedchuk** [comment]
retest this please

**Comment by AVandana-OSI** [comment]
It's ok for temp, but let us check with @wmitchell-cambria or @TylerOSI too.

**Comment by wmitchell-cambria** [comment]
I would prefer if we disabled the test, rather than removing the file. Otherwise, Hotline functionality is on hold for a while, so removing it seems OK. (If it is removed permanently, a story should be created to add it back, once Hotline is started up again.)

**Pull request closed without merging**
