### PR TITLE
(WIP) SNAP-712 - Display 'Unable To Determine' race as 'Unknown'

### PR DESCRIPTION
**Pull request by wmitchell-cambria**
### Jira Story

- [Race shows "Undefined" value SNAP-712](https://osi-cwds.atlassian.net/browse/SNAP-712)

## Description

More specifically, when a client in legacy has the ethnicity "Unable to Determine", it currently shows up in CARES as "undefined - Unable to Determine". This should make it "Unknown - Unknown". There is another story (SNAP-204) to remove that duplicate value in this and other cases.

## Tests
- [ ] I have included unit tests 
- [ ] I have included feature tests 
- [ ] I have included other tests 
- [x] I have NOT included tests 

I should create a feature test for this before merging. Will do on Monday.

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (No behavioral changes)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have ran all tests for the project.
- [ ] I have ran lint/rubocop check for the changed/new files.
- [ ] My code is in a stable state ready to be deployable, but not necessarily complete.
- [ ] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by wmitchell-cambria** [comment]
Also TODO on this:  This fix is clearly related to hardcoding the LOV for Intake. A story should be created to correct these values on the backend, so that we do not reintroduce this behavior should we ever return to using the LOV service.

**Comment by wmitchell-cambria** [comment]
retest this please

**Comment by wmitchell-cambria** [comment]
Hmm, Jenkins is not picking up on the build. Retest this please.

**Comment by SashaKyz** [comment]
retest this please

**Pull request closed without merging**
