### PR TITLE
HOT-2166 Align Create new person and Show more result side by side

### PR DESCRIPTION
**Pull request by pokharelmanish**
### Jira Story

- [Show More Results and +Create New Person buttons should be displayed side by side](https://osi-cwds.atlassian.net/browse/HOT-2166)

## Description
Show More Results and Create New Person buttons should be displayed side by side

Before Fix
screen shot 2018-09-17 at 9 24 05 am

After Fix
screen shot 2018-09-17 at 9 22 55 am

ScreenShot in IE
screen shot 2018-09-17 at 2 16 05 pm

## Tests
- [x] I have included unit tests 
- [ ] I have included feature tests 
- [ ] I have included other tests 
- [ ] I have NOT included tests 

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (No behavioral changes)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have ran all tests for the project.
- [x] I have ran lint/rubocop check for the changed/new files.
- [x] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by pokharelmanish** [comment]
@TylerOSI Yeah it's responsive. I will add a unit test. Thanks

**Comment by NagaPradeepGajula-osi** [comment]
restart this please

**Comment by NagaPradeepGajula-osi** [comment]
Thanks for the specs and screenshots after the changes.

**Comment by NagaPradeepGajula-osi** [comment]
retest this please

**Comment by pokharelmanish** [comment]
retest this please

**Comment by pokharelmanish** [comment]
retest this please

**Comment by pokharelmanish** [comment]
retest this please

**Pull request merged**
