### PR TITLE
SNAP-1028 No Blank Chars in Masked Input Field

### PR DESCRIPTION
**Pull request by ggomez-cambriasolutions**
### Jira Story

https://osi-cwds.atlassian.net/browse/SNAP-1028

## Description
This PR adds logic to the Masked Input Field component to place the cursor in the next available blank position. 

This prevents users from entering blank characters in the field.

## Tests
- [x] I have included unit tests 
- [ ] I have included feature tests 
- [ ] I have included other tests 
- [ ] I have NOT included tests 

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have ran all tests for the project.
- [x] I have ran lint/rubocop check for the changed/new files.
- [ ] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by pokharelmanish** [comment]
Question: With this approach now we no longer can used left/right arrow key inside the field if we want to delete a digit. 

Step 1: Type `7111111111111111118` in ClientId field.
Screen Shot 2019-04-09 at 1 11 26 PM

Now let's say I am trying to change the number `7` digit to `1`. The only way i can change is to delete all the number and type again `1111111111111111118`

Previous Behaviour: 
You can use the left arrow key to navigate to digit `7` and delete digit `7` and type `1`.

**Comment by wmitchell-cambria** [comment]
If y'all are not already working closely with DesignOps on this one, you definitely should. I would also double check that Capybara and screen readers can interact with the field properly.

**Comment by ggomez-cambriasolutions** [comment]
@wmitchell-cambria Design Ops is working on a component for longer term use. This is a short-term solution until they are ready to release the new component.

**Comment by ggomez-cambriasolutions** [comment]
@pokharelmanish You are correct. However, Q/A and PO are ok with the new behavior.

**Comment by pokharelmanish** [comment]
@ggomez-cambriasolutions ok, then it looks good to me.

**Pull request merged**
