### PR TITLE
Disable accessibility check - feature person age validation

### PR DESCRIPTION
**Pull request by ratneshraval**
### Jira Story

- [SNAP-825](https://osi-cwds.atlassian.net/browse/snap-825)

## Description
- Disable accessibility check for person age validation test.

## Tests
- [ ] I have included unit tests 
- [ ] I have included feature tests 
- [ ] I have included other tests 
- [x] I have NOT included tests 

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (No behavioral changes)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have ran all tests for the project.
- [ ] I have ran lint/rubocop check for the changed/new files.
- [ ] My code is in a stable state ready to be deployable, but not necessarily complete.
- [ ] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by ratneshraval** [comment]
retest this please

**Comment by NagaPradeepGajula-osi** [comment]
+1 ^^

**Comment by ratneshraval** [comment]
@wmitchell-cambria  I added in description why I'm disabling the check. Someone more familiar with intake should create story to reinstate this.

**Comment by wmitchell-cambria** [comment]
https://osi-cwds.atlassian.net/browse/HOT-2626

**Pull request merged**
