### PR TITLE
HOT-2106. Remove system code sorting by code.

### PR DESCRIPTION
**Pull request by LotharII**
### Jira Story

- [Consistently sort LOV codes in the user-desired order HOT-2106](https://osi-cwds.atlassian.net/browse/HOT-2106)

## Description
Removed system-codes sorting by the numeric code.

## Tests
- [x] I have included unit tests 
- [ ] I have included feature tests 
- [ ] I have included other tests 
- [ ] I have NOT included tests 

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have ran all tests for the project.
- [x] I have ran lint/rubocop check for the changed/new files.
- [x] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by wmitchell-cambria** [comment]
Is the API-side sorting in place yet? I feel like removing this could cause unexpected issues until we can trust the order of the system codes we receive.

**Comment by LotharII** [comment]
@will

> Is the API-side sorting in place yet? I feel like removing this could cause unexpected issues until we can trust the order of the system codes we receive.

Yes, there is already sorting by category and intake_code fields in API.

**Comment by LotharII** [comment]
retest this please

**Comment by will** [comment]
I have no idea!!!

**Comment by wmitchell-cambria** [comment]
Name buddies!

@LotharII - OK, sounds good to me.

**Pull request merged**
