### PR TITLE
HOT-2002 Updated config webpacker.yml to work also on windows

### PR DESCRIPTION
**Pull request by pokharelmanish**
### Jira Story

- [Intake app fails on Windows when binding webpack-dev-server to 0.0.0.0](https://osi-cwds.atlassian.net/browse/HOT-2002)

## Description
Updated config/webpacker.yml to work also on a windows machine.

## Tests
- [ ] I have included unit tests 
- [ ] I have included feature tests 
- [ ] I have included other tests 
- [x] I have NOT included tests 

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have ran all tests for the project.
- [x] I have ran lint/rubocop check for the changed/new files.
- [x] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by wmitchell-cambria** [comment]
Before merging this, we should get as many of our devs as we can to check out this branch and try it.

**Comment by pokharelmanish** [comment]
retest this please

**Comment by wmitchell-cambria** [comment]
Might it? I'm skeptical.

**Comment by TylerOSI** [comment]
💯 i totally prefer localhost over a broadcast address

**Pull request merged**
