### PR TITLE
SNAP-976 Update Person Search By Name Query Builder

### PR DESCRIPTION
**Pull request by ggomez-cambriasolutions**
### Jira Story

https://osi-cwds.atlassian.net/browse/SNAP-976

## Description
Updates the Person Search By Name query builder to the latest iteration authored by @david-smith-osi.

## Tests
- [x] I have included unit tests 
- [ ] I have included feature tests 
- [ ] I have included other tests 
- [ ] I have NOT included tests 

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have ran all tests for the project.
- [x] I have ran lint/rubocop check for the changed/new files.
- [ ] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by ggomez-cambriasolutions** [comment]
`{
    "track_scores": "true",
    "sort": [
      {
        "_score": "desc",
        "last_name": "asc",
        "first_name": "asc",
        "_uid": "desc"
      }
    ],
    "_source": [
      "id",
      "legacy_source_table",
      "first_name",
      "middle_name",
      "last_name",
      "name_suffix",
      "gender",
      "akas",
      "date_of_birth",
      "date_of_death",
      "ssn",
      "languages",
      "races",
      "ethnicity",
      "client_counties",
      "addresses.id",
      "addresses.effective_start_date",
      "addresses.street_name",
      "addresses.street_number",
      "addresses.city",
      "addresses.county",
      "addresses.state_code",
      "addresses.zip",
      "addresses.type",
      "addresses.legacy_descriptor",
      "addresses.phone_numbers.number",
      "addresses.phone_numbers.type",
      "csec.start_date",
      "csec.end_date",
      "csec.csec_code_id",
      "csec.description",
      "legacy_descriptor",
      "highlight",
      "phone_numbers.id",
      "phone_numbers.number",
      "phone_numbers.type",
      "sensitivity_indicator",
      "race_ethnicity",
      "open_case_responsible_agency_code"
    ],
    "highlight": {
      "order": "score",
      "number_of_fragments": "10",
      "require_field_match": "false",
      "fields": {
        "autocomplete_search_bar": {
          "matched_fields": [
            "autocomplete_search_bar",
            "autocomplete_search_bar.phonetic",
            "autocomplete_search_bar.diminutive"
          ]
        },
        "searchable_date_of_birth": {}
      }
    },
    "size": 10,
    "min_score": 2.5,
    "query": {
      "function_score": {
        "query": {
          "bool": {
            "must": [
              {
                "match": {
                  "legacy_descriptor.legacy_table_name": {
                    "query": "CLIENT_T"
                  }
                }
              }
            ]
          }
        },
        "functions": [
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "LAST_NAME",
                      "_name": "1_m_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name": {
                        "query": "FIRST_NAME",
                      "_name": "1_m_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 16384
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "multi_match": {
                      "query": 'last name suffix',
                      "operator": 'and',
                      "fields": [
                        'last_name',
                        'suffix'
                      ],
                    "type": 'cross_fields',
                    "_name": '2_mlt_last_suffix'
                    }
                  }
                ]
              }
            },
            "weight": 8192
          },
          {
            "filter": {
              "multi_match": {
                "query": "LAST_NAME FIRST_NAME",
                "operator": "and",
                "fields": [
                  "akas.first_name",
                  "akas.last_name"
                ],
                "type": "cross_fields",
                "_name": "3_mult_aka"
              }
            },
            "weight": 4096
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "LAST_NAME",
                        "_name": "4_dim_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name.diminutive": {
                        "query": "FIRST_NAME",
                        "_name": "4_dim_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 2048
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "LAST_NAME",
                        "_name": "5_pho_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name.phonetic": {
                        "query": "FIRST_NAME",
                        "_name": "5_pho_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 1024
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "LAST_NAME",
                        "_name": "6_fz_lst"
                      }
                    }
                  },
                  {
                    "fuzzy": {
                      "first_name": {
                        "value": "FIRST_NAME",
                        "fuzziness": 5,
                        "prefix_length": 1,
                        "max_expansions": 25,
                        "_name": "6_fz_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 512
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "LAST_NAME",
                        "_name": "7_prt_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name_ngram": {
                        "query": "FIRST_NAME",
                        "minimum_should_match": "25%",
                        "_name": "7_prt_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 256
          },
          {
            "filter": {
              "multi_match": {
                "query": "FIRST_NAME LAST_NAME",
                "operator": "and",
                "fields": [
                  "first_name",
                  "last_name"
                ],
                "fuzziness": "2",
                "_name": "7_mult_fz"
              }
            },
            "weight": 200
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "FIRST_NAME",
                        "_name": "9a_rev_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name": {
                        "query": "LAST_NAME",
                        "_name": "9a_rev_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 128
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "FIRST_NAME",
                        "_name": "9b_rev_prt_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name_ngram": {
                        "query": "LAST_NAME",
                        "minimum_should_match": "25%",
                        "_name": "9b_rev_prt_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 64
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "LAST_NAME",
                        "_name": "10_dup_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name": {
                        "query": "LAST_NAME",
                        "_name": "10_dup_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 32
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name_ngram": {
                        "query": "FIRST_NAME",
                        "minimum_should_match": "25%",
                        "_name": "11_rev_prt_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name_ngram": {
                        "query": "LAST_NAME",
                        "minimum_should_match": "25%",
                        "_name": "11_rev_prt_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 16
          },
          {
            "filter": {
              "match": {
                "last_name": {
                  "query": "LAST_NAME",
                  "_name": "8_m_lst"
                }
              }
            },
            "weight": 12
          },
          {
            "filter": {
              "match": {
                "first_name": {
                  "query": "FIRST_NAME",
                  "_name": "xb_m_fst"
                }
              }
            },
            "weight": 8
          }
        ],
        "score_mode": "sum",
        "boost_mode": "sum"
      }
    }
  }`

**Comment by ggomez-cambriasolutions** [comment]
`{
    "track_scores": "true",
    "sort": [
      {
        "_score": "desc",
        "last_name": "asc",
        "first_name": "asc",
        "_uid": "desc"
      }
    ],
    "_source": [
      "id",
      "legacy_source_table",
      "first_name",
      "middle_name",
      "last_name",
      "name_suffix",
      "gender",
      "akas",
      "date_of_birth",
      "date_of_death",
      "ssn",
      "languages",
      "races",
      "ethnicity",
      "client_counties",
      "addresses.id",
      "addresses.effective_start_date",
      "addresses.street_name",
      "addresses.street_number",
      "addresses.city",
      "addresses.county",
      "addresses.state_code",
      "addresses.zip",
      "addresses.type",
      "addresses.legacy_descriptor",
      "addresses.phone_numbers.number",
      "addresses.phone_numbers.type",
      "csec.start_date",
      "csec.end_date",
      "csec.csec_code_id",
      "csec.description",
      "legacy_descriptor",
      "highlight",
      "phone_numbers.id",
      "phone_numbers.number",
      "phone_numbers.type",
      "sensitivity_indicator",
      "race_ethnicity",
      "open_case_responsible_agency_code"
    ],
    "highlight": {
      "order": "score",
      "number_of_fragments": "10",
      "require_field_match": "false",
      "fields": {
        "autocomplete_search_bar": {
          "matched_fields": [
            "autocomplete_search_bar",
            "autocomplete_search_bar.phonetic",
            "autocomplete_search_bar.diminutive"
          ]
        },
        "searchable_date_of_birth": {}
      }
    },
    "size": 10,
    "min_score": 2.5,
    "query": {
      "function_score": {
        "query": {
          "bool": {
            "must": [
              {
                "match": {
                  "legacy_descriptor.legacy_table_name": {
                    "query": "CLIENT_T"
                  }
                }
              }
            ]
          }
        },
        "functions": [
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "LAST_NAME",
                      "_name": "1_m_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name": {
                        "query": "FIRST_NAME",
                      "_name": "1_m_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 16384
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "multi_match": {
                      "query": "last name suffix",
                      "operator": "and",
                      "fields": [
                        "last_name",
                        "suffix"
                      ],
                    "type": "cross_fields",
                    "_name": "2_mlt_last_suffix"
                    }
                  }
                ]
              }
            },
            "weight": 8192
          },
          {
            "filter": {
              "multi_match": {
                "query": "LAST_NAME FIRST_NAME",
                "operator": "and",
                "fields": [
                  "akas.first_name",
                  "akas.last_name"
                ],
                "type": "cross_fields",
                "_name": "3_mult_aka"
              }
            },
            "weight": 4096
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "LAST_NAME",
                        "_name": "4_dim_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name.diminutive": {
                        "query": "FIRST_NAME",
                        "_name": "4_dim_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 2048
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "LAST_NAME",
                        "_name": "5_pho_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name.phonetic": {
                        "query": "FIRST_NAME",
                        "_name": "5_pho_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 1024
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "LAST_NAME",
                        "_name": "6_fz_lst"
                      }
                    }
                  },
                  {
                    "fuzzy": {
                      "first_name": {
                        "value": "FIRST_NAME",
                        "fuzziness": 5,
                        "prefix_length": 1,
                        "max_expansions": 25,
                        "_name": "6_fz_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 512
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "LAST_NAME",
                        "_name": "7_prt_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name_ngram": {
                        "query": "FIRST_NAME",
                        "minimum_should_match": "25%",
                        "_name": "7_prt_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 256
          },
          {
            "filter": {
              "multi_match": {
                "query": "FIRST_NAME LAST_NAME",
                "operator": "and",
                "fields": [
                  "first_name",
                  "last_name"
                ],
                "fuzziness": "2",
                "_name": "7_mult_fz"
              }
            },
            "weight": 200
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "FIRST_NAME",
                        "_name": "9a_rev_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name": {
                        "query": "LAST_NAME",
                        "_name": "9a_rev_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 128
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "FIRST_NAME",
                        "_name": "9b_rev_prt_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name_ngram": {
                        "query": "LAST_NAME",
                        "minimum_should_match": "25%",
                        "_name": "9b_rev_prt_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 64
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name": {
                        "query": "LAST_NAME",
                        "_name": "10_dup_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name": {
                        "query": "LAST_NAME",
                        "_name": "10_dup_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 32
          },
          {
            "filter": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "last_name_ngram": {
                        "query": "FIRST_NAME",
                        "minimum_should_match": "25%",
                        "_name": "11_rev_prt_lst"
                      }
                    }
                  },
                  {
                    "match": {
                      "first_name_ngram": {
                        "query": "LAST_NAME",
                        "minimum_should_match": "25%",
                        "_name": "11_rev_prt_fst"
                      }
                    }
                  }
                ]
              }
            },
            "weight": 16
          },
          {
            "filter": {
              "match": {
                "last_name": {
                  "query": "LAST_NAME",
                  "_name": "8_m_lst"
                }
              }
            },
            "weight": 12
          },
          {
            "filter": {
              "match": {
                "first_name": {
                  "query": "FIRST_NAME",
                  "_name": "xb_m_fst"
                }
              }
            },
            "weight": 8
          }
        ],
        "score_mode": "sum",
        "boost_mode": "sum"
      }
    }
}`

**Comment by pokharelmanish** [comment]
yeah, I agree with @NagaPradeepGajula-osi. We need descriptive names.

**Comment by ggomez-cambriasolutions** [comment]
@NagaPradeepGajula-osi I shorted the names because I ran into limits on length of lines, as well as the total lines. After talking to @pokharelmanish, we decided to break up this query builder into two modules, so that we can give these methods more readable names.

**Pull request merged**
