### PR TITLE
Fit 571 update babel webpack configs

### PR DESCRIPTION
**Pull request by NagaPradeepGajula-osi**
### Jira Story

- (https://osi-cwds.atlassian.net/browse/FIT-571)

## Description
Update babel dependencies to use version 7 and make the related config changes. Istanbul code coverage config was removed via this PR temporarily as this is blocking the CL components consumption. It will be added back once we find how to config it without crashing the app due to new changes.

## Tests
- [ ] I have included unit tests 
- [ ] I have included feature tests 
- [ ] I have included other tests 
- [x] I have NOT included tests 
Config changes on so no tests are being included

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have ran all tests for the project.
- [x] I have ran lint/rubocop check for the changed/new files.
- [x] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by wmitchell-cambria** [comment]
With the Istanbul loader removed, is coverage still generated for test reports? I think they showed up in Jenkins somewhere.

**Comment by NagaPradeepGajula-osi** [comment]
retest this please

**Comment by NagaPradeepGajula-osi** [comment]
@wmitchell-cambria Once the build is done I will look into it and I believe the coverage would be no longer be available. But the idea is to add it back once we figure it out.

**Comment by wmitchell-cambria** [comment]
OK, seems like a good plan.

**Comment by wmitchell-cambria** [comment]
Yeah, looks like the JS test coverage stats were lost. It also looks like Ruby coverage stats were lost at some point as well.

I'm a little concerned about that, because it also looks like Intake has been slowly losing test coverage over time. It's hard to say, though, because it's difficult to track when builds are not saved and we didn't often look at the stats even when they were generated.

So, I think I'm fine with merging this, but perhaps a story is in order to generate code coverage statistics in a way where they are visible and able to be tracked over time.

**Comment by NagaPradeepGajula-osi** [comment]
@wmitchell-cambria totally agree with you I am writing up a story and once done I will link  it here with this PR too.

**Comment by NagaPradeepGajula-osi** [comment]
Here is the story for adding back the code coverage. https://osi-cwds.atlassian.net/browse/SNAP-1061https://osi-cwds.atlassian.net/browse/SNAP-1061

**Pull request merged**
