### PR TITLE
Display Search Criteria in Autompleter Suggestion Header

### PR DESCRIPTION
**Pull request by ggomez-cambriasolutions**
### Jira Story

No story - Bug Fix

## Description
This PR will take the search criteria and display it in the suggestion header.

## Tests
- [x] I have included unit tests 
- [ ] I have included feature tests 
- [ ] I have included other tests 
- [ ] I have NOT included tests 

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have ran all tests for the project.
- [x] I have ran lint/rubocop check for the changed/new files.
- [ ] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by pokharelmanish** [comment]
@ggomez-cambriasolutions FYI 
For a single search bar, I see this
screen shot 2019-03-06 at 12 57 22 pm

**Comment by ggomez-cambriasolutions** [comment]
Great catch, @pokharelmanish.

**Comment by ggomez-cambriasolutions** [comment]
screen shot 2019-03-06 at 2 44 38 pm

**Comment by ggomez-cambriasolutions** [comment]
screen shot 2019-03-06 at 2 47 10 pm

**Pull request merged**
