### PR TITLE
SNAP-983 - Search by SSN

### PR DESCRIPTION
**Pull request by zemlyanoi**
### Jira Story
https://osi-cwds.atlassian.net/browse/SNAP-983

## Description
filter by SSN to get an exact match on a client that exists in the system.

## Tests
- [x] I have included unit tests 
- [ ] I have included feature tests 
- [ ] I have included other tests 
- [ ] I have NOT included tests 

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have ran all tests for the project.
- [ ] I have ran lint/rubocop check for the changed/new files.
- [ ] My code is in a stable state ready to be deployable, but not necessarily complete.
- [ ] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by pokharelmanish** [comment]
@zemlyanoi Few questions: 

USE CASE  1: 
What if the user enters DOB and SSN??
I see no results found but the client of this SSN in the database. 
Screen Shot 2019-03-11 at 1 31 21 PM

This is the client 
Screen Shot 2019-03-11 at 1 31 33 PM

USE CASE 2: 
What if the user enters Client ID and SSN (This could be the question for PO)
Both are a unique identifier. So we need to decide which one should have the highest priority??

Screen Shot 2019-03-11 at 1 31 44 PM

**Comment by zemlyanoi** [comment]
DOB is 3/1/1991

**Comment by zemlyanoi** [comment]
I am going to discuss with Sri about SSN and Date of Birth

**Comment by zemlyanoi** [comment]
will create new PR

**Pull request closed without merging**
