### PR TITLE
SNAP-437 Added missing header and link

### PR DESCRIPTION
**Pull request by pokharelmanish**
### Jira Story

- [Missing Header and Link on Conditions of Use Page](https://osi-cwds.atlassian.net/browse/SNAP-437)

## Description
Fixed Missing Header and Link on Conditions of Use Page
Visual change after fix in JIRA.

## Tests
- [ ] I have included unit tests 
- [ ] I have included feature tests 
- [ ] I have included other tests 
- [x] I have NOT included tests 

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (No behavioral changes)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have ran all tests for the project.
- [x] I have ran lint/rubocop check for the changed/new files.
- [x] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by pokharelmanish** [comment]
retest this please

**Comment by vikas199** [comment]
retest this please

**Comment by pokharelmanish** [comment]
Come on retest this please

**Comment by wmitchell-cambria** [comment]
Jenkins, retest this please.

**Pull request merged**
