### PR TITLE
HOT-2508 Merge participant creation into one implementation

### PR DESCRIPTION
**Pull request by mariamcws**
## Description

Merge participant creation into one implementation
There is no call from Intake to
POST `/screenings/#{screening_id}/participants`
However, there is a call to POST `/screenings/#{screening_id}/participant`
In this story we will remove `/screenings/#{screening_id}/participant`
and move over the functionality to POST `/screenings/#{screening_id}/participants`
Ferb is internally calling the related service for `/screenings/#{screening_id}/participants`
so we will keep that functionality as well in a different method than create

## Jira Issue link

[Merge participant creation into one implementation](https://osi-cwds.atlassian.net/browse/HOT-2508)

## Tests
- [x] I have included unit tests 
- [ ] I have included functional tests 
- [ ] I have included other tests 
- [ ] I have NOT included tests 

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the google code style of this project.
- [x] I have ran all tests for the project.
- [x] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check SonarQube after the build completes, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by mariamcws** [comment]
retest this please

**Comment by mariamcws** [comment]
retest this please

**Comment by mariamcws** [comment]
retest please

**Comment by mariamcws** [comment]
retest please

**Comment by mariamcws** [comment]
retest this please

**Comment by mariamcws** [comment]
retest this please

**Comment by amanbop** [comment]
This has broken our relationships functionality again. This is twice in two days. We must find a better way to do this.

**Comment by wmitchell-cambria** [comment]
For those watching along, after some more testing, the Attach Link issue was tracked down as a front-end bug and fixed in #935. We spent a few more days testing Mariam's work on the merged endpoints, so we feel comfortable deploying them again in #944.

**Pull request merged**
