### PR TITLE
Update Rails for security patches

### PR DESCRIPTION
**Pull request by wmitchell-cambria**
### Jira Story

- No story, flagged by GitHub (on CANS)

## Description

This update is in response to the following security vuln patches:
https://weblog.rubyonrails.org/2018/11/27/Rails-4-2-5-0-5-1-5-2-have-been-released/

## Tests
- [ ] I have included unit tests 
- [ ] I have included feature tests 
- [ ] I have included other tests 
- [x] I have NOT included tests 

Dependency update only.

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have ran all tests for the project.
- [ ] I have ran lint/rubocop check for the changed/new files.
- [ ] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by NagaPradeepGajula-osi** [comment]
I saw Denys comment on updating the base image of cwds/ruby any thought on it?

**Comment by wmitchell-cambria** [comment]
Yeah, that's a good catch. Confirming with @ratneshraval. I think we should update the base image as well.

**Comment by wmitchell-cambria** [comment]
retest this please

**Comment by TylerOSI** [comment]
yay! no test failures

**Pull request merged**
