### PR TITLE
initial commit for SemVer

### PR DESCRIPTION
**Pull request by AVandana-OSI**
### Jira Story
https://osi-cwds.atlassian.net/browse/FIT-284

## Description
Imported the JenkinsUtils library and used the Semver to update the version.

## Tests
- [ ] I have included unit tests 
- [ ] I have included feature tests 
- [ ] I have included other tests 
- [x] I have NOT included tests 
Changes are in JenkinsFile

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have ran all tests for the project.
- [x] I have ran lint/rubocop check for the changed/new files.
- [x] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by wmitchell-cambria** [comment]
Just be careful, even on a separate branch. If this makes git tags, it will still affect the master build numbering. You should also double check that this does not trigger a Preint deploy. (These are actual issues that have occurred in the past.)

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Pull request merged**
