### PR TITLE
[WIP] Int 533 direct user functionality based on role

### PR DESCRIPTION
**Pull request by brunoOSI**
### Jira Story

- [Hotline - Direct user functionality based on role INT-533](https://osi-cwds.atlassian.net/browse/INT-533)

## Description
This will show/hide Hotline and/or Snapshot UI elements based on the permissions for each user. 

## Tests
- [x] I have included unit tests 
- [x] I have included feature tests 
- [ ] I have included other tests 
- [ ] I have NOT included tests 

## Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

Listing is as "Breaking" because the usual bare bones privileges for users will not allow you to see anything. 

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have ran all tests for the project.
- [x] I have ran lint/rubocop check for the changed/new files.
- [x] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by brunoOSI** [comment]
retest this please

**Comment by brunoOSI** [comment]
retest this please

**Comment by brunoOSI** [comment]
retest this please

**Comment by brunoOSI** [comment]
retest this please

**Comment by brunoOSI** [comment]
retest this please

**Comment by brunoOSI** [comment]
retest this please

**Comment by TylerOSI** [comment]
closing this in favor of ca-cwds/intake#629

**Pull request closed without merging**
